// Generated by assets/sprites/generate.py -- do not edit.
// Source: BoldGlyphs6x7.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t bold_glyphs_data_start[] asm("_binary_bold_glyphs_bwb_start");
extern const uint8_t bold_glyphs_data_end[] asm("_binary_bold_glyphs_bwb_end");

struct FontBold : FontSheet {
  FontBold() : FontSheet(bold_glyphs_data_start, bold_glyphs_data_end, 32) {}
};

// global instance as there is no instance state
inline const FontBold font_bold;
