// Generated by assets/sprites/generate.py -- do not edit.
// Source: Cloud.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t cloud_data_start[] asm("_binary_cloud_bwb_start");
extern const uint8_t cloud_data_end[] asm("_binary_cloud_bwb_end");

struct CloudSprite : SingleSprite {
  CloudSprite() : SingleSprite(cloud_data_start, cloud_data_end) {}
};

// global instance as there is no instance state
inline const CloudSprite cloud_sprite;
