// Generated by assets/sprites/generate.py -- do not edit.
// Source: Firework.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t firework_data_start[] asm("_binary_firework_bwb_start");
extern const uint8_t firework_data_end[] asm("_binary_firework_bwb_end");

struct FireworkAnimation : AnimationSheet {
  FireworkAnimation() : AnimationSheet(firework_data_start, firework_data_end) {}
};
