// Generated by assets/sprites/generate.py -- do not edit.
// Source: Heart.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t heart_data_start[] asm("_binary_heart_bwb_start");
extern const uint8_t heart_data_end[] asm("_binary_heart_bwb_end");

struct HeartAnimation : AnimationSheet {
  HeartAnimation() : AnimationSheet(heart_data_start, heart_data_end) {}
};
