// Generated by assets/sprites/generate.py -- do not edit.
// Source: MoonSmall.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t moon_small_data_start[] asm("_binary_moon_small_bwb_start");
extern const uint8_t moon_small_data_end[] asm("_binary_moon_small_bwb_end");

struct MoonAtlas : TextureAtlas {
  MoonAtlas() : TextureAtlas(moon_small_data_start, moon_small_data_end) {}
};

// global instance as there is no instance state
inline const MoonAtlas moon_atlas;
