// Generated by assets/sprites/generate.py -- do not edit.
// Source: Rain.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t rain_data_start[] asm("_binary_rain_bwb_start");
extern const uint8_t rain_data_end[] asm("_binary_rain_bwb_end");

struct RainAnimation : AnimationSheet {
  RainAnimation() : AnimationSheet(rain_data_start, rain_data_end) {}
};
