# Generated by assets/sprites/generate.py -- do not edit.
set(OBG_SPRITE_EMBED_FILES
    "../data/cloud.bwb"
    "../data/wifi.bwb"
    "../data/moon_small.bwb"
    "../data/bold_glyphs.bwb"
    "../data/thin_glyphs.bwb"
    "../data/sun.bwb"
    "../data/rain.bwb"
    "../data/heart.bwb"
    "../data/firework.bwb"
)
