// Generated by assets/sprites/generate.py -- do not edit.
// Source: Sun.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t sun_data_start[] asm("_binary_sun_bwb_start");
extern const uint8_t sun_data_end[] asm("_binary_sun_bwb_end");

struct SunAnimation : AnimationSheet {
  SunAnimation() : AnimationSheet(sun_data_start, sun_data_end) {}
};
