// Generated by assets/sprites/generate.py -- do not edit.
// Source: ThinGlyphs4x6.ase
#pragma once

#include "sprites.hpp"

extern const uint8_t thin_glyphs_data_start[] asm("_binary_thin_glyphs_bwb_start");
extern const uint8_t thin_glyphs_data_end[] asm("_binary_thin_glyphs_bwb_end");

struct ThinFont : FontSheet {
  ThinFont() : FontSheet(thin_glyphs_data_start, thin_glyphs_data_end, 32) {}
};

// global instance as there is no instance state
inline const ThinFont font_thin;
