#!/usr/bin/env python3
"""Generate sprite blobs, C++ wrappers and the CMake embed list from sprites.toml.

For every entry in the manifest this writes:

    data/<name>.bwb             the blob embedded in the firmware
    main/sprites/<name>.hpp     extern declarations, wrapper struct, global
    main/sprites/sprites.cmake  the EMBED_FILES list for main/CMakeLists.txt

Run with --check to verify the committed files match the sources without
writing anything (exit status 1 if any is stale or missing).
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

import img2bwb

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
MANIFEST = HERE / "sprites.toml"
DATA_DIR = REPO / "data"
HEADER_DIR = REPO / "main" / "sprites"
CMAKE_FILE = HEADER_DIR / "sprites.cmake"

KIND_BASE = {
    "single": "SingleSprite",
    "atlas": "TextureAtlas",
    "font": "FontSheet",
    "animation": "AnimationSheet",
}

GENERATED_BY = "assets/sprites/generate.py"


def load_manifest() -> list[dict]:
    with MANIFEST.open("rb") as fh:
        manifest = tomllib.load(fh)
    sprites = manifest.get("sprite", [])
    if not sprites:
        raise SystemExit(f"{MANIFEST}: no [[sprite]] entries")
    for entry in sprites:
        for key in ("name", "source", "kind", "type"):
            if key not in entry:
                raise SystemExit(f"sprite {entry.get('name', '?')}: missing '{key}'")
        if entry["kind"] not in KIND_BASE:
            raise SystemExit(f"sprite {entry['name']}: unknown kind '{entry['kind']}'")
        if entry["kind"] == "font" and "ascii_start" not in entry:
            raise SystemExit(f"sprite {entry['name']}: fonts need 'ascii_start'")
        if (HERE / entry["source"]).suffix.lower() not in (".ase", ".aseprite"):
            raise SystemExit(f"sprite {entry['name']}: source must be a .ase file")
    return sprites


def header_text(entry: dict) -> str:
    name = entry["name"]
    kind = entry["kind"]
    type_name = entry["type"]
    base = KIND_BASE[kind]
    start = f"{name}_data_start"
    end = f"{name}_data_end"

    lines = [
        f"// Generated by {GENERATED_BY} -- do not edit.",
        f"// Source: {entry['source']}",
        "#pragma once",
        "",
        '#include "sprites.hpp"',
        "",
        f'extern const uint8_t {start}[] asm("_binary_{name}_bwb_start");',
        f'extern const uint8_t {end}[] asm("_binary_{name}_bwb_end");',
        "",
        f"struct {type_name} : {base} {{",
    ]
    if kind == "font":
        lines.append(
            f"  {type_name}() : FontSheet({start}, {end}, {entry['ascii_start']}) {{}}"
        )
    else:
        lines.append(f"  {type_name}() : {base}({start}, {end}) {{}}")
    lines.append("};")
    if "instance" in entry:
        lines += [
            "",
            "// global instance as there is no instance state",
            f"inline const {type_name} {entry['instance']};",
        ]
    return "\n".join(lines) + "\n"


def cmake_text(entries: list[dict]) -> str:
    lines = [f"# Generated by {GENERATED_BY} -- do not edit.", "set(OBG_SPRITE_EMBED_FILES"]
    lines += [f'    "../data/{entry["name"]}.bwb"' for entry in entries]
    lines.append(")")
    return "\n".join(lines) + "\n"


def build(entries: list[dict]) -> dict[Path, bytes]:
    """Return every generated file as path -> bytes."""
    outputs: dict[Path, bytes] = {}
    for entry in entries:
        source = HERE / entry["source"]
        if not source.exists():
            raise SystemExit(f"sprite {entry['name']}: source {source} not found")
        cell = entry.get("cell")
        try:
            blob = img2bwb.encode(source, cell[0] if cell else None, cell[1] if cell else None)
        except ValueError as exc:
            raise SystemExit(f"sprite {entry['name']}: {exc}") from exc
        outputs[DATA_DIR / f"{entry['name']}.bwb"] = blob
        outputs[HEADER_DIR / f"{entry['name']}.hpp"] = header_text(entry).encode()
    outputs[CMAKE_FILE] = cmake_text(entries).encode()
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="report stale files instead of writing"
    )
    args = parser.parse_args(argv)

    entries = load_manifest()
    outputs = build(entries)

    stale = []
    for path, content in outputs.items():
        if args.check:
            current = path.read_bytes() if path.exists() else None
            if current != content:
                stale.append(path)
        else:
            path.write_bytes(content)
            print(f"wrote {path.relative_to(REPO)}")

    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(REPO)}", file=sys.stderr)
        if stale:
            return 1
        print(f"all generated files match {MANIFEST.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
